// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:fea03007-9dfb-4689-991b-747a1b7fb1c1',
    'aws_cognito_region': 'us-east-1',
    'aws_mobile_analytics_app_id': 'da8f69d65f1a4b17b046ecbe65e738b8',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'e779e07f-c6da-4c16-9a09-8b00a0a927c3',
    'aws_project_name': 'freelance sms',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'freelancesms-mobilehub-1696733753',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_wRR9s216a',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '3i3r0lkf3cha4tqv090j2dq5jl',
}

export default awsmobile;
